# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=labBack
      - DB_PASSWORD=somekindofpassword
      - DB_NAME=labBack
      - DB_PORT=5432

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: labBack
      POSTGRES_PASSWORD: somekindofpassword
      POSTGRES_DB: labBack
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
